theme: jekyll-theme-minimal
title: Swan Valley RCACS 519
description: This is a unofficial cadet-ran website. This site will host information for cadets that need it.
logo: https://www.aircadetleaguemb.ca/badges/519sqn2.png
